const AREAS=['TI','Fiscal','Contábil','Faturamento','Recebimento','Financeiro','Compras'];
const STATUS={new:'Novo',analysis:'Em análise',action:'Ação necessária',homologation:'Homologação',implemented:'Implementado',not_applicable:'Não aplicável'};
const ORIGIN={official:'Oficial',provider:'TOTVS',interpretation:'Debiasi',internal:'Interno'};
const VIEW_META={home:['O que precisa de atenção?','Veja primeiro as ações, depois os detalhes.'],updates:['Pendências e atualizações','Filtre somente o que importa para sua rotina.'],timeline:['Cronograma','Datas confirmadas e próximos marcos em uma linha do tempo.'],areas:['Visão por área','O que muda no trabalho de cada time.'],sources:['Fontes e rastreabilidade','De onde veio cada informação e se a coleta está saudável.']};
const state={events:[],sources:[],statuses:{},lastRun:null,view:'home',area:localStorage.getItem('radar-area')||'Todas',areaFocus:'TI'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=v=>{if(!v)return'—';const d=new Date(v.length===10?`${v}T12:00:00`:v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString('pt-BR')};
const fmtShort=v=>{if(!v)return null;const d=new Date(`${v.slice(0,10)}T12:00:00`);if(Number.isNaN(d.getTime()))return null;return{day:String(d.getDate()).padStart(2,'0'),month:d.toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}};
const fmtDateTime=v=>v?new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
async function api(path='/api/dashboard',options={}){const r=await fetch(path,{headers:{'content-type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
const active=e=>!['implemented','not_applicable'].includes(e.status);
const matchesArea=e=>state.area==='Todas'||(e.areas||[]).includes(state.area);
const chip=(text,cls='')=>`<span class="chip ${cls}">${esc(text)}</span>`;
const sourceChip=e=>chip(ORIGIN[e.origin]||e.origin,e.origin);
const statusChip=e=>chip(STATUS[e.status]||e.status,e.status);
function areaAction(e,area=state.area){if(area==='TI')return e.actions?.ti;if(['Fiscal','Contábil'].includes(area))return e.actions?.fiscal;if(area==='Todas')return e.actions?.ti||e.actions?.fiscal||e.actions?.user;return e.actions?.user}
function rank(e){const u={high:0,medium:1,low:2}[e.urgency]??1;const s={action:0,homologation:1,new:2,analysis:3}[e.status]??4;return u*10+s}
function urgencyLabel(u){return u==='high'?'Alta':u==='low'?'Baixa':'Média'}
function attentionCard(e){const action=areaAction(e)||e.summary;return `<article class="attention-card" data-event="${esc(e.id)}"><i class="priority-bar ${esc(e.urgency)}"></i><div><h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p><div class="attention-action"><b>Próxima ação:</b> ${esc(action||'Validar impacto e responsável.')}</div><div class="chips">${sourceChip(e)}${statusChip(e)}${(e.areas||[]).slice(0,3).map(a=>chip(a)).join('')}</div></div><div class="attention-side"><time>${fmtDate(e.effectiveDate||e.detectedAt)}</time>${chip(`${urgencyLabel(e.urgency)} prioridade`)}</div></article>`}
function renderHome(){const filtered=state.events.filter(matchesArea);const act=filtered.filter(active);const attention=act.filter(e=>e.status==='action'||e.urgency==='high').length;const fresh=act.filter(e=>e.status==='new').length;const testing=act.filter(e=>e.status==='homologation').length;const done=filtered.filter(e=>e.status==='implemented').length;$('#heroMetrics').innerHTML=[['Ação agora',attention,'Itens de maior impacto','!',true],['Novidades',fresh,'Aguardando triagem','●'],['Em teste',testing,'Homologação','✓'],['Concluídos',done,'Implementados internamente','↗']].map(([a,b,c,d,p])=>`<div class="hero-card ${p?'primary':''}"><span class="metric-icon">${d}</span><span class="metric-label">${a}</span><strong>${b}</strong><small>${c}</small></div>`).join('');
 const list=[...act].sort((a,b)=>rank(a)-rank(b)||new Date(b.detectedAt)-new Date(a.detectedAt)).slice(0,6);$('#attentionList').innerHTML=list.length?list.map(attentionCard).join(''):`<div class="empty-state"><b>Nada exigindo ação nesta visão.</b><span>Itens concluídos continuam no histórico.</span></div>`;
 const dated=act.filter(e=>e.effectiveDate).sort((a,b)=>a.effectiveDate.localeCompare(b.effectiveDate)).slice(0,5);$('#deadlineList').innerHTML=dated.length?dated.map(e=>{const d=fmtShort(e.effectiveDate);return `<div class="deadline-item" data-event="${esc(e.id)}"><div class="date-box"><b>${d?.day||'--'}</b><span>${d?.month||''}</span></div><div><h4>${esc(e.title)}</h4><p>${esc((e.areas||[]).slice(0,3).join(' · '))}</p></div></div>`}).join(''):`<div class="empty-state"><b>Sem vigências futuras confirmadas.</b><span>O Radar não inventa datas ausentes da fonte.</span></div>`;
 const max=Math.max(1,...AREAS.map(a=>act.filter(e=>(e.areas||[]).includes(a)).length));$('#areaOverview').innerHTML=AREAS.map(a=>{const n=act.filter(e=>(e.areas||[]).includes(a)).length;return `<div class="area-card" data-area="${a}"><strong>${n}</strong><span>${a}</span><div class="progress"><i style="width:${Math.round(n/max*100)}%"></i></div></div>`}).join('');
 $('#navPendingCount').textContent=act.length;
}
function renderUpdates(){const q=$('#searchInput')?.value.toLowerCase().trim()||'';const uf=$('#urgencyFilter')?.value||'all',of=$('#originFilter')?.value||'all',sf=$('#statusFilter')?.value||'active';let list=state.events.filter(matchesArea).filter(e=>{const hay=[e.title,e.summary,e.whatChanged,e.sourceName,...(e.areas||[]),e.datasul?.module,e.datasul?.program,e.responsible].join(' ').toLowerCase();return(!q||hay.includes(q))&&(uf==='all'||e.urgency===uf)&&(of==='all'||e.origin===of)&&(sf==='all'||(sf==='active'?active(e):e.status===sf))});list.sort((a,b)=>rank(a)-rank(b)||new Date(b.detectedAt)-new Date(a.detectedAt));$('#resultsCount').textContent=`${list.length} registro${list.length===1?'':'s'}`;$('#allEvents').innerHTML=list.length?list.map(e=>`<article class="event-row" data-event="${esc(e.id)}"><div><h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p><div class="chips">${sourceChip(e)}${statusChip(e)}</div></div><div><span class="event-cell-label">Áreas</span><div class="event-areas">${(e.areas||[]).slice(0,4).map(a=>chip(a)).join('')}</div></div><div><span class="event-cell-label">Prioridade</span>${chip(urgencyLabel(e.urgency),e.urgency==='high'?'action':'')}</div><div><span class="event-cell-label">Data</span><span class="muted">${fmtDate(e.effectiveDate||e.detectedAt)}</span></div></article>`).join(''):`<div class="empty-state"><b>Nenhum registro para estes filtros.</b><span>Altere os filtros ou a visão de área.</span></div>`}
function renderTimeline(){const list=state.events.filter(matchesArea).filter(active);const dated=list.filter(e=>e.effectiveDate).sort((a,b)=>a.effectiveDate.localeCompare(b.effectiveDate));const undated=list.filter(e=>!e.effectiveDate).sort((a,b)=>new Date(b.detectedAt)-new Date(a.detectedAt));let html=dated.map(e=>`<article class="timeline-item" data-event="${esc(e.id)}"><span class="timeline-date">${fmtDate(e.effectiveDate)}</span><h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p><div class="chips">${sourceChip(e)}${(e.areas||[]).slice(0,3).map(a=>chip(a)).join('')}</div></article>`).join('');html+=`<div class="timeline-undated"><p class="eyebrow">SEM VIGÊNCIA CONFIRMADA</p>${undated.length?undated.slice(0,20).map(e=>`<article class="timeline-item" data-event="${esc(e.id)}"><span class="timeline-date">Detectado em ${fmtDate(e.detectedAt)}</span><h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p></article>`).join(''):`<div class="empty-state"><b>Nenhum item sem data.</b></div>`}</div>`;$('#timelineList').innerHTML=html||`<div class="empty-state"><b>Sem itens ativos.</b></div>`}
function renderAreas(){if(!AREAS.includes(state.areaFocus))state.areaFocus='TI';$('#areaTabs').innerHTML=AREAS.map(a=>`<button class="area-tab ${a===state.areaFocus?'active':''}" data-area-tab="${a}">${a}</button>`).join('');const items=state.events.filter(e=>(e.areas||[]).includes(state.areaFocus)&&active(e)).sort((a,b)=>rank(a)-rank(b));$('#areaFocus').innerHTML=`<div class="area-focus-header"><div><h3>${state.areaFocus}</h3><p>${items.length} item${items.length===1?'':'s'} em aberto para esta área.</p></div>${chip(items.filter(e=>e.urgency==='high').length+' alta prioridade')}</div><div class="area-focus-list">${items.length?items.map(e=>`<article class="area-item" data-event="${esc(e.id)}"><div><h4>${esc(e.title)}</h4><p>${esc(e.summary)}</p><div class="chips">${sourceChip(e)}${statusChip(e)}</div></div><div class="area-specific-action"><b>O que ${state.areaFocus} precisa fazer</b>${esc(areaAction(e,state.areaFocus)||'Aguardar orientação interna ou validar se há impacto.')}</div></article>`).join(''):`<div class="empty-state"><b>Nenhuma pendência para ${state.areaFocus}.</b></div>`}</div>`}
function renderSources(){const order={error:0,blocked:1,pending:2,ok:3,manual:4};const list=[...state.sources].sort((a,b)=>(order[(state.statuses[a.id]?.state)||(a.monitor==='manual'?'manual':'pending')]??5)-(order[(state.statuses[b.id]?.state)||(b.monitor==='manual'?'manual':'pending')]??5));$('#sourcesGrid').innerHTML=list.map(s=>{const st=state.statuses[s.id]||{state:s.monitor==='manual'?'manual':'pending',message:s.monitor==='manual'?'Inclusão manual':'Aguardando primeira coleta'};return `<article class="source-card"><div class="source-head"><i class="source-health-dot ${esc(st.state)}"></i><div><p class="eyebrow">${esc(s.group)}</p><h3>${esc(s.name)}</h3></div>${chip(ORIGIN[s.origin]||s.origin,s.origin)}</div><p>${esc(s.description)}</p><p><b>${esc(st.message||'')}</b>${st.lastChecked?` · última tentativa ${fmtDateTime(st.lastChecked)}`:''}</p>${s.url?`<a class="source-link" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">Abrir fonte original ↗</a>`:''}</article>`}).join('')}
function renderHealth(){const monitored=state.sources.filter(s=>s.monitor!=='manual');const bad=monitored.filter(s=>['blocked','error'].includes(state.statuses[s.id]?.state)).length;const pending=monitored.filter(s=>!state.statuses[s.id]||state.statuses[s.id]?.state==='pending').length;const b=$('#healthBanner');if(!state.lastRun){b.className='health-banner loading';$('#healthTitle').textContent='Aguardando a primeira coleta automática';$('#healthText').textContent=pending?`${pending} fontes ainda sem linha de base.`:'As fontes ainda não foram executadas.';return}if(bad){b.className='health-banner warn';$('#healthTitle').textContent=`${bad} fonte${bad===1?'':'s'} precisa${bad===1?'':'m'} de atenção`;$('#healthText').textContent=`Última coleta ${fmtDateTime(state.lastRun.finishedAt)} · ${state.lastRun.created||0} novidade(s).`;return}b.className='health-banner ok';$('#healthTitle').textContent='Coleta automática saudável';$('#healthText').textContent=`Última coleta ${fmtDateTime(state.lastRun.finishedAt)} · ${state.lastRun.created||0} novidade(s) · ${state.lastRun.ok||0} fontes OK.`}
function render(){renderHealth();renderHome();renderUpdates();renderTimeline();renderAreas();renderSources();bindCards();$('#currentArea').textContent=state.area==='Todas'?'Todas as áreas':state.area}
function bindCards(){$$('[data-event]').forEach(el=>el.onclick=()=>openEvent(el.dataset.event));$$('[data-area]').forEach(el=>el.onclick=()=>{state.areaFocus=el.dataset.area;go('areas')});$$('[data-area-tab]').forEach(el=>el.onclick=()=>{state.areaFocus=el.dataset.areaTab;renderAreas();bindCards()})}
function go(view){state.view=view;$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${view}View`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const [t,s]=VIEW_META[view]||VIEW_META.home;$('#viewTitle').textContent=t;$('#viewSubtitle').textContent=s;render();window.scrollTo({top:0,behavior:'smooth'})}
function openEvent(id){const e=state.events.find(x=>x.id===id);if(!e)return;$('#detailChips').innerHTML=`${sourceChip(e)} ${statusChip(e)} ${chip(urgencyLabel(e.urgency)+' prioridade')}`;const when=e.effectiveDate?`Vigência ${fmtDate(e.effectiveDate)}`:e.publishedAt?`Publicado ${fmtDate(e.publishedAt)}`:'Sem vigência confirmada';$('#eventDetail').innerHTML=`<h2 class="detail-title">${esc(e.title)}</h2><p class="detail-lead">${esc(e.summary)}</p><div class="chips">${(e.areas||[]).map(a=>chip(a)).join('')}${e.automatic?chip('Detectado automaticamente'):''}</div><div class="decision-strip"><div class="decision-card"><b>O que mudou?</b><p>${esc(e.whatChanged||e.summary)}</p></div><div class="decision-card"><b>Quando?</b><p>${esc(when)}</p></div><div class="decision-card"><b>Quem?</b><p>${esc((e.areas||[]).join(', ')||'A validar')}</p></div></div><div class="detail-section"><h3>Ação prática</h3><div class="action-grid"><div class="action-card"><b>TI</b><p>${esc(e.actions?.ti||'Sem ação definida.')}</p></div><div class="action-card"><b>Fiscal / Contábil</b><p>${esc(e.actions?.fiscal||'Sem ação definida.')}</p></div><div class="action-card"><b>Usuário da área</b><p>${esc(e.actions?.user||'Sem ação definida.')}</p></div></div></div><div class="detail-section"><h3>Evidência</h3><div class="evidence-box">${esc(e.evidence||'Consulte a fonte original.')}</div>${e.sourceUrl?`<p><a class="source-link" target="_blank" rel="noopener noreferrer" href="${esc(e.sourceUrl)}">Abrir ${esc(e.sourceName)} ↗</a></p>`:''}</div><div class="detail-admin"><label>Status<select id="detailStatus">${Object.entries(STATUS).map(([k,v])=>`<option value="${k}" ${e.status===k?'selected':''}>${v}</option>`).join('')}</select></label><label>Responsável<input id="detailResponsible" value="${esc(e.responsible||'')}" placeholder="Nome / área" /></label><label style="grid-column:1/-1">Notas internas<textarea id="detailNotes" rows="3">${esc(e.notes||'')}</textarea></label><div style="grid-column:1/-1;text-align:right"><button id="saveDetail" class="primary-btn" type="button">Salvar acompanhamento</button></div></div>`;$('#eventDialog').showModal();$('#saveDetail').onclick=async()=>{try{await api('/api/dashboard',{method:'PATCH',body:JSON.stringify({id:e.id,status:$('#detailStatus').value,responsible:$('#detailResponsible').value,notes:$('#detailNotes').value})});toast('Acompanhamento salvo.');$('#eventDialog').close();await load()}catch(err){toast(err.message)}}}
function buildAreaPicker(){const items=['Todas',...AREAS];$('#areaPicker').innerHTML=items.map(a=>`<button type="button" class="area-pick ${a===state.area?'active':''}" data-pick-area="${a}">${a==='Todas'?'Todas as áreas':a}</button>`).join('');$$('[data-pick-area]').forEach(b=>b.onclick=()=>{state.area=b.dataset.pickArea;localStorage.setItem('radar-area',state.area);$('#areaDialog').close();render()})}
async function load(){try{const data=await api();state.events=data.events||[];state.sources=data.sources||[];state.statuses=data.statuses||{};state.lastRun=data.lastRun||null;render()}catch(err){$('#healthBanner').className='health-banner error';$('#healthTitle').textContent='Não foi possível carregar o Radar';$('#healthText').textContent=err.message;toast(err.message)}}
$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#healthDetailsBtn').onclick=()=>go('sources');$('#areaChooser').onclick=()=>{buildAreaPicker();$('#areaDialog').showModal()};['#searchInput','#urgencyFilter','#originFilter','#statusFilter'].forEach(s=>$(s)?.addEventListener('input',()=>{renderUpdates();bindCards()}));
$('#newManualBtn').onclick=()=>$('#manualDialog').showModal();$('#closeManual').onclick=$('#cancelManual').onclick=()=>$('#manualDialog').close();$('#manualAreas').innerHTML=AREAS.map(a=>`<label><input type="checkbox" name="areas" value="${a}">${a}</label>`).join('');$('#manualForm').onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(ev.currentTarget);const body={sourceId:fd.get('sourceId'),title:fd.get('title'),summary:fd.get('summary'),effectiveDate:fd.get('effectiveDate')||undefined,urgency:fd.get('urgency'),areas:fd.getAll('areas'),actions:{ti:fd.get('actionTi'),fiscal:fd.get('actionFiscal'),user:fd.get('actionUser')},evidence:fd.get('evidence')};try{await api('/api/dashboard',{method:'POST',body:JSON.stringify(body)});ev.currentTarget.reset();$('#manualDialog').close();toast('Orientação registrada.');await load()}catch(err){toast(err.message)}};
go('home');load();
