type Origin = 'official'|'provider'|'interpretation'|'internal';
type EventStatus = 'new'|'analysis'|'action'|'homologation'|'implemented'|'not_applicable';
type Urgency = 'low'|'medium'|'high';
type Source = {id:string;name:string;shortName:string;group:string;origin:Origin;url:string;alternates?:string[];monitor:'full'|'filtered'|'manual';keywords?:string[];areas:string[];description:string};
type RadarEvent = {id:string;sourceId:string;sourceName:string;sourceUrl:string;origin:Origin;title:string;summary:string;whatChanged:string;effectiveDate?:string;publishedAt?:string;detectedAt:string;urgency:Urgency;status:EventStatus;areas:string[];datasul?:{module?:string;program?:string;release?:string};actions:{ti?:string;fiscal?:string;user?:string};evidence?:string;responsible?:string;notes?:string;automatic:boolean;fingerprint?:string};
interface Env { DB:D1Database; AI:Ai; ASSETS:Fetcher; COLLECTOR_TOKEN?:string; APP_TIMEZONE?:string }

const SOURCES:Source[]=[
{id:'rfb-legislacao',name:'Receita Federal — Legislação da Reforma Tributária do Consumo',shortName:'RFB · Legislação',group:'Legal',origin:'official',url:'https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/acoes-e-programas/programas-e-atividades/reforma-tributaria-do-consumo/legislacao/legislacao-da-reforma-tributaria-do-consumo',monitor:'filtered',keywords:['IBS','CBS','Lei Complementar','Ato Conjunto','Ato Técnico','Decreto','Portaria','Reforma Tributária'],areas:['Fiscal','Contábil','TI'],description:'Fonte primária para novos atos, leis, decretos e normas da RTC.'},
{id:'rfb-orientacoes-2026',name:'Receita Federal — Orientações da Reforma Tributária para 2026',shortName:'RFB · Orientações 2026',group:'Legal',origin:'official',url:'https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/acoes-e-programas/programas-e-atividades/reforma-tributaria-do-consumo/orientacoes-2026',monitor:'filtered',keywords:['IBS','CBS','documentos fiscais','obrig','2026','Reforma Tributária'],areas:['Fiscal','Contábil','Faturamento','Recebimento','TI'],description:'Orientações operacionais oficiais da Receita para o período de transição.'},
{id:'cgibs',name:'Comitê Gestor do IBS — Reforma Tributária',shortName:'CGIBS',group:'Legal',origin:'official',url:'https://www.cgibs.gov.br/',monitor:'filtered',keywords:['IBS','CBS','Reforma Tributária','Regulamento','Resolução','Ato Conjunto','documento fiscal'],areas:['Fiscal','Contábil','TI'],description:'Publicações e atos do Comitê Gestor do IBS.'},
{id:'nfe-nt',name:'Portal NF-e — Notas Técnicas vigentes',shortName:'NF-e · Notas Técnicas',group:'Documentos Fiscais',origin:'official',url:'https://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?AspxAutoDetectCookieSupport=1&tipoConteudo=6WfrpZYE4Ik%3D',monitor:'filtered',keywords:['Reforma Tributária','RTC','IBS','CBS','2025.002','classificação tributária','cClassTrib'],areas:['Fiscal','Faturamento','Recebimento','TI'],description:'Mudanças de leiaute, schemas e regras da NF-e/NFC-e relacionadas à RTC.'},
{id:'totvs-cronograma-simples',name:'TOTVS TDN — Reforma Tributária · Cronograma de Entregas · Linha Datasul',shortName:'Datasul · Cronograma',group:'Datasul',origin:'provider',url:'https://tdn.totvs.com/pages/releaseview.action?pageId=976133881',alternates:['https://tdn.totvs.com/plugins/viewsource/viewpagesrc.action?pageId=976133881','https://tdn.totvs.com/rest/api/content/976133881?expand=body.storage,version,title'],monitor:'full',areas:['TI','Fiscal','Faturamento','Recebimento','Financeiro','Compras','Contábil'],description:'Visão resumida das entregas Datasul para a Reforma Tributária.'},
{id:'totvs-cronograma-detalhado',name:'TOTVS TDN — Cronograma Detalhado · Reforma Tributária Datasul',shortName:'Datasul · Cronograma detalhado',group:'Datasul',origin:'provider',url:'https://tdn.totvs.com/pages/releaseview.action?pageId=946421605',alternates:['https://tdn.totvs.com/plugins/viewsource/viewpagesrc.action?pageId=946421605','https://tdn.totvs.com/rest/api/content/946421605?expand=body.storage,version,title'],monitor:'full',areas:['TI','Fiscal','Faturamento','Recebimento','Financeiro','Compras','Contábil'],description:'Detalhes técnicos de módulo, programa, entrega e previsão.'},
{id:'totvs-impactos',name:'TOTVS TDN — Reforma Tributária Datasul · Impactos por área',shortName:'Datasul · Impactos',group:'Datasul',origin:'provider',url:'https://tdn.totvs.com/pages/releaseview.action?pageId=974814078',alternates:['https://tdn.totvs.com/plugins/viewsource/viewpagesrc.action?pageId=974814078','https://tdn.totvs.com/rest/api/content/974814078?expand=body.storage,version,title'],monitor:'full',areas:['TI','Fiscal','Faturamento','Recebimento','Financeiro','Compras','Contábil'],description:'O que já foi entregue e o que ainda será entregue por área do Datasul.'},
{id:'totvs-espaco-legislacao',name:'TOTVS — Espaço Legislação · Reforma Tributária',shortName:'TOTVS · Espaço Legislação',group:'Datasul',origin:'provider',url:'https://espacolegislacao.totvs.com/reforma-tributaria/',alternates:['https://espacolegislacao.totvs.com/feed/'],monitor:'filtered',keywords:['Reforma Tributária','IBS','CBS','Datasul','documento fiscal','Nota Técnica'],areas:['TI','Fiscal','Contábil'],description:'Visão geral da TOTVS sobre legislação e impactos nos produtos.'},
{id:'debiasi',name:'Debiasi — Auditoria / interpretação fiscal-contábil',shortName:'Debiasi',group:'Consultoria',origin:'interpretation',url:'',monitor:'manual',areas:['Fiscal','Contábil','TI'],description:'Orientações recebidas da auditoria. Inclusão manual para preservar contexto e evidência.'}
];

const BASELINE:RadarEvent[]=[
{id:'baseline-2026-obrigacoes',sourceId:'rfb-orientacoes-2026',sourceName:'Receita Federal — Orientações da Reforma Tributária para 2026',sourceUrl:SOURCES[1].url,origin:'official',title:'2026: IBS e CBS já fazem parte da adaptação operacional',summary:'A Receita orienta que 2026 é o primeiro ano operacional da transição, com IBS e CBS nos documentos fiscais conforme os leiautes aplicáveis.',whatChanged:'Os novos tributos passaram a exigir adaptação de documentos fiscais, sistemas e rotinas durante 2026.',publishedAt:'2025-12-12',detectedAt:'2026-09-17T15:00:00Z',urgency:'high',status:'analysis',areas:['Fiscal','Faturamento','Recebimento','TI'],actions:{ti:'Confirmar versões/patches necessários do Datasul e manter cenários de homologação.',fiscal:'Validar parametrizações de IBS/CBS e regras aplicáveis às operações da empresa.',user:'Seguir somente as orientações homologadas; não alterar regra tributária por conta própria.'},evidence:'Baseline oficial para iniciar o Radar; o status interno deve ser validado pela empresa.',automatic:false},
{id:'baseline-legislacao',sourceId:'rfb-legislacao',sourceName:'Receita Federal — Legislação da Reforma Tributária do Consumo',sourceUrl:SOURCES[0].url,origin:'official',title:'Base legal central da Reforma Tributária do Consumo',summary:'A página oficial concentra os principais marcos regulatórios e atos conjuntos da RTC e é tratada como fonte primária do Radar.',whatChanged:'O Radar acompanha a página oficial para detectar novos atos, decretos, portarias e alterações relevantes.',detectedAt:'2026-09-17T15:00:00Z',urgency:'medium',status:'analysis',areas:['Fiscal','Contábil','TI'],actions:{ti:'Monitorar impacto sistêmico somente após identificar mudança efetiva.',fiscal:'Avaliar aplicabilidade das novas normas à operação da empresa.',user:'Nenhuma ação até existir orientação interna específica.'},evidence:'Fonte oficial da Receita Federal incluída como referência legal principal.',automatic:false},
{id:'baseline-nfe-rtc',sourceId:'nfe-nt',sourceName:'Portal NF-e — Notas Técnicas vigentes',sourceUrl:SOURCES[3].url,origin:'official',title:'NF-e/NFC-e: Nota Técnica 2025.002 é referência para adequações da RTC',summary:'O Portal NF-e publica versões da NT 2025.002 com alterações de leiaute e validações referentes à Reforma Tributária do Consumo.',whatChanged:'O Radar vigia versões e atualizações ligadas a IBS, CBS, classificação tributária e regras de validação.',publishedAt:'2026-06-03',detectedAt:'2026-09-17T15:00:00Z',urgency:'high',status:'analysis',areas:['Fiscal','Faturamento','Recebimento','TI'],actions:{ti:'Relacionar novas versões de NT aos patches e entregas correspondentes do Datasul.',fiscal:'Validar as regras tributárias e tabelas aplicáveis.',user:'Aplicar o processo homologado; novas rejeições devem ser direcionadas ao Fiscal/TI.'},evidence:'Baseline técnica; o coletor detectará novas versões ou conteúdo relevante publicado no Portal NF-e.',automatic:false},
{id:'baseline-totvs',sourceId:'totvs-cronograma-simples',sourceName:'TOTVS TDN — Reforma Tributária · Cronograma de Entregas · Linha Datasul',sourceUrl:SOURCES[4].url,origin:'provider',title:'Datasul: cronogramas e impactos são a referência técnica do ERP',summary:'O Radar usa os cronogramas simples/detalhado e a página de impactos do Datasul para relacionar mudanças legais às entregas do ERP.',whatChanged:'As três páginas TDN indicadas pela empresa foram cadastradas como fontes prioritárias de fornecedor.',detectedAt:'2026-09-17T15:00:00Z',urgency:'medium',status:'analysis',areas:['TI','Fiscal','Faturamento','Recebimento','Financeiro','Compras','Contábil'],actions:{ti:'Conferir versão, patch, programa e disponibilidade sempre que o Radar detectar mudança no cronograma.',fiscal:'Validar se a entrega técnica cobre a regra tributária aplicável.',user:'Receber somente a orientação prática referente à sua rotina.'},evidence:'Fonte de fornecedor. Não substitui legislação nem validação fiscal.',automatic:false}
];

function json(data:unknown,status=200){return Response.json(data,{status,headers:{'cache-control':'no-store'}})}
function now(){return new Date().toISOString()}
function uid(prefix='evt'){return `${prefix}-${crypto.randomUUID()}`}
async function sha(text:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function safeJson<T>(raw:string|null,fallback:T):T{try{return raw?JSON.parse(raw):fallback}catch{return fallback}}
function cleanText(input:string){return input.slice(0,220000).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/\s+/g,' ').trim()}
function normalize(text:string,source:Source){const clean=cleanText(text).replace(/\b\d{1,2}:\d{2}:\d{2}\b/g,'');if(source.monitor!=='filtered'||!source.keywords?.length)return clean.slice(0,160000);const low=clean.toLocaleLowerCase('pt-BR');const windows:string[]=[];for(const kw of source.keywords){let from=0,k=kw.toLocaleLowerCase('pt-BR'),idx=-1,hits=0;while((idx=low.indexOf(k,from))>=0&&hits<12){windows.push(clean.slice(Math.max(0,idx-260),Math.min(clean.length,idx+520)));from=idx+k.length;hits++}}return(windows.length?[...new Set(windows)].join('\n'):clean).slice(0,100000)}
function changed(previous:string,current:string){const split=(t:string)=>t.split(/\n+|(?<=[.!?;])\s+/).map(s=>s.trim()).filter(s=>s.length>=35&&s.length<=1200);const old=new Set(split(previous).map(s=>s.toLocaleLowerCase('pt-BR')));return split(current).filter(s=>!old.has(s.toLocaleLowerCase('pt-BR'))).slice(0,14)}
function inferAreas(text:string,fallback:string[]=[]){const low=text.toLocaleLowerCase('pt-BR');const map:[string,string[]][]=[['Faturamento',['faturamento','nf-e','nfc-e','danfe','emissão','nota fiscal']],['Recebimento',['recebimento','entrada','fornecedor','cte','ct-e']],['Fiscal',['fiscal','tribut','ibs','cbs','cst','cclasstrib','apuração']],['Contábil',['contáb','contabil','razão','lançamento contábil']],['Financeiro',['financeiro','contas a pagar','contas a receber','pagamento']],['Compras',['compras','pedido de compra','suprimentos']],['TI',['datasul','erp','patch','release','programa','schema','xml','layout','leiaute']]];const found=map.filter(([,terms])=>terms.some(t=>low.includes(t))).map(([a])=>a);return [...new Set(found.length?found:fallback)].slice(0,7)}
function sanitize(input:Partial<RadarEvent>):RadarEvent{const statuses:EventStatus[]=['new','analysis','action','homologation','implemented','not_applicable'],urgencies:Urgency[]=['low','medium','high'];return{id:String(input.id||uid()),sourceId:String(input.sourceId||'internal'),sourceName:String(input.sourceName||'Registro interno'),sourceUrl:String(input.sourceUrl||''),origin:(['official','provider','interpretation','internal'].includes(String(input.origin))?input.origin:'internal') as Origin,title:String(input.title||'Sem título').slice(0,240),summary:String(input.summary||'').slice(0,1600),whatChanged:String(input.whatChanged||input.summary||'').slice(0,2500),effectiveDate:input.effectiveDate?String(input.effectiveDate).slice(0,40):undefined,publishedAt:input.publishedAt?String(input.publishedAt).slice(0,40):undefined,detectedAt:input.detectedAt||now(),urgency:urgencies.includes(input.urgency as Urgency)?input.urgency as Urgency:'medium',status:statuses.includes(input.status as EventStatus)?input.status as EventStatus:'new',areas:Array.isArray(input.areas)?[...new Set(input.areas.map(String))].slice(0,10):[],datasul:input.datasul||{},actions:input.actions||{},evidence:input.evidence?String(input.evidence).slice(0,4000):undefined,responsible:input.responsible?String(input.responsible).slice(0,160):undefined,notes:input.notes?String(input.notes).slice(0,3000):undefined,automatic:Boolean(input.automatic),fingerprint:input.fingerprint}}
function rowToEvent(r:any):RadarEvent{return{id:r.id,sourceId:r.source_id,sourceName:r.source_name,sourceUrl:r.source_url,origin:r.origin,title:r.title,summary:r.summary,whatChanged:r.what_changed,effectiveDate:r.effective_date||undefined,publishedAt:r.published_at||undefined,detectedAt:r.detected_at,urgency:r.urgency,status:r.status,areas:safeJson(r.areas_json,[]),datasul:safeJson(r.datasul_json,{}),actions:safeJson(r.actions_json,{}),evidence:r.evidence||undefined,responsible:r.responsible||undefined,notes:r.notes||undefined,automatic:Boolean(r.automatic),fingerprint:r.fingerprint||undefined}}
async function insertEvent(env:Env,e:RadarEvent){await env.DB.prepare(`INSERT OR IGNORE INTO events (id,source_id,source_name,source_url,origin,title,summary,what_changed,effective_date,published_at,detected_at,urgency,status,areas_json,datasul_json,actions_json,evidence,responsible,notes,automatic,fingerprint) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(e.id,e.sourceId,e.sourceName,e.sourceUrl,e.origin,e.title,e.summary,e.whatChanged,e.effectiveDate||null,e.publishedAt||null,e.detectedAt,e.urgency,e.status,JSON.stringify(e.areas),JSON.stringify(e.datasul||{}),JSON.stringify(e.actions||{}),e.evidence||null,e.responsible||null,e.notes||null,e.automatic?1:0,e.fingerprint||null).run()}
async function ensureSeed(env:Env){const row=await env.DB.prepare('SELECT COUNT(*) AS n FROM events').first<any>();if(Number(row?.n||0)===0)for(const e of BASELINE)await insertEvent(env,e)}
async function dashboard(env:Env){await ensureSeed(env);const er=await env.DB.prepare('SELECT * FROM events ORDER BY detected_at DESC LIMIT 800').all<any>();const sr=await env.DB.prepare('SELECT * FROM source_status').all<any>();const mr=await env.DB.prepare("SELECT value_json FROM meta WHERE key='last-run'").first<any>();const statuses:Record<string,any>={};for(const r of sr.results||[])statuses[r.source_id]={state:r.state,message:r.message,lastChecked:r.last_checked,lastSuccess:r.last_success,httpStatus:r.http_status,usedUrl:r.used_url};for(const s of SOURCES)if(s.monitor==='manual')statuses[s.id]={state:'manual',message:'Inclusão manual',lastChecked:null};return{events:(er.results||[]).map(rowToEvent),sources:SOURCES,statuses,lastRun:safeJson(mr?.value_json||null,null)}}
async function saveManual(env:Env,body:any){const source=SOURCES.find(s=>s.id===body.sourceId);const e=sanitize({id:uid('manual'),sourceId:source?.id||body.sourceId||'internal',sourceName:source?.name||body.sourceName||'Registro interno',sourceUrl:source?.url||body.sourceUrl||'',origin:source?.origin||body.origin||'internal',title:body.title,summary:body.summary,whatChanged:body.whatChanged||body.summary,effectiveDate:body.effectiveDate,publishedAt:body.publishedAt,urgency:body.urgency||'medium',status:body.status||'analysis',areas:body.areas||[],datasul:body.datasul,actions:body.actions||{},evidence:body.evidence,responsible:body.responsible,notes:body.notes,detectedAt:now(),automatic:false});await insertEvent(env,e);return e}
async function patchEvent(env:Env,body:any){const found=await env.DB.prepare('SELECT * FROM events WHERE id=?').bind(body.id).first<any>();if(!found)return null;const e=sanitize({...rowToEvent(found),status:body.status??found.status,urgency:body.urgency??found.urgency,responsible:body.responsible??found.responsible,notes:body.notes??found.notes});await env.DB.prepare('UPDATE events SET status=?,urgency=?,responsible=?,notes=? WHERE id=?').bind(e.status,e.urgency,e.responsible||null,e.notes||null,e.id).run();return e}
async function fetchSource(source:Source){let lastStatus=0,lastMessage='Sem URL';for(const url of [source.url,...(source.alternates||[])].filter(Boolean)){try{const c=new AbortController(),timer=setTimeout(()=>c.abort(),9000);const r=await fetch(url,{signal:c.signal,headers:{'user-agent':'Mozilla/5.0 (compatible; ReformaDatasulRadar/2.0)','accept':'text/html,application/xhtml+xml,application/json,*/*;q=0.8','accept-language':'pt-BR,pt;q=0.9','cache-control':'no-cache'},redirect:'follow'});clearTimeout(timer);lastStatus=r.status;if(!r.ok){lastMessage=`HTTP ${r.status}`;continue}let text=await r.text();if((r.headers.get('content-type')||'').includes('application/json')||text.trim().startsWith('{'))try{const j=JSON.parse(text);text=[j?.title,j?.body?.storage?.value,j?.version?.when].filter(Boolean).join('\n')||text}catch{}if(/just a moment|cf-chl|access denied|forbidden/i.test(text.slice(0,4500))){lastMessage='Proteção antirobô detectada';continue}if(text.trim().length<120){lastMessage='Conteúdo vazio ou insuficiente';continue}return{text,usedUrl:url,httpStatus:r.status}}catch(err:any){lastMessage=err?.name==='AbortError'?'Tempo de resposta excedido':(err?.message||String(err))}}const e:any=new Error(lastMessage);e.status=lastStatus;throw e}
function fallbackAnalysis(source:Source,snippets:string[]):Partial<RadarEvent>{const joined=snippets.join(' ').slice(0,8000),areas=inferAreas(joined,source.areas),title=snippets[0]?.replace(/\s+/g,' ').slice(0,110)||`Alteração detectada em ${source.shortName}`,technical=/patch|release|datasul|programa|schema|xml|leiaute|layout/i.test(joined),deadline=/prazo|vigência|obrigat|a partir de|data de|cronograma/i.test(joined);return{title:`Mudança detectada · ${source.shortName}: ${title}`,summary:'A fonte monitorada mudou. O conteúdo precisa ser conferido antes de qualquer decisão fiscal ou sistêmica.',whatChanged:snippets.slice(0,4).join(' ').slice(0,2200),urgency:deadline?'high':technical?'medium':'medium',areas,actions:{ti:source.group==='Datasul'||technical?'Conferir se a alteração exige versão, patch, programa ou parametrização no Datasul.':'Avaliar se existe impacto sistêmico.',fiscal:'Validar a aplicabilidade da mudança e definir a regra tributária antes da configuração.',user:'Nenhuma mudança de processo até existir orientação interna validada.'}}}
async function analyze(env:Env,source:Source,snippets:string[]){const fallback=fallbackAnalysis(source,snippets);try{const prompt=`Você classifica mudanças sobre a Reforma Tributária do Consumo para uma empresa que usa TOTVS Datasul. Seja curto, leigo e direto. Não invente prazo, programa, versão, obrigação ou impacto. Diferencie fonte oficial de fornecedor. Retorne APENAS JSON válido com: title, summary, whatChanged, effectiveDate (YYYY-MM-DD ou null), urgency (low|medium|high), areas (array entre TI,Fiscal,Contábil,Faturamento,Recebimento,Financeiro,Compras), datasul {module,program,release} com null quando desconhecido, actions {ti,fiscal,user}. Toda conclusão não explícita deve ser ação de validação, nunca fato.\n\nFonte: ${source.name}\nTipo: ${source.origin==='official'?'OFICIAL':'FORNECEDOR'}\nTrechos novos/alterados:\n${snippets.join('\n---\n').slice(0,12000)}`;const resp:any=await env.AI.run('@cf/meta/llama-3.1-8b-instruct-fast',{messages:[{role:'user',content:prompt}],max_tokens:900,temperature:0.1});const raw=String(resp?.response||resp?.result?.response||'').replace(/^```json\s*/i,'').replace(/```$/,'').trim();const parsed=JSON.parse(raw);return{...fallback,...parsed,urgency:['low','medium','high'].includes(parsed.urgency)?parsed.urgency:fallback.urgency,areas:Array.isArray(parsed.areas)&&parsed.areas.length?parsed.areas:fallback.areas,actions:{...fallback.actions,...(parsed.actions||{})}}}catch(err){console.log('AI fallback',err);return fallback}}
async function upsertStatus(env:Env,sourceId:string,data:any){await env.DB.prepare(`INSERT INTO source_status (source_id,state,message,last_checked,last_success,http_status,used_url) VALUES (?,?,?,?,?,?,?) ON CONFLICT(source_id) DO UPDATE SET state=excluded.state,message=excluded.message,last_checked=excluded.last_checked,last_success=COALESCE(excluded.last_success,source_status.last_success),http_status=excluded.http_status,used_url=COALESCE(excluded.used_url,source_status.used_url)`).bind(sourceId,data.state,data.message,data.lastChecked||null,data.lastSuccess||null,data.httpStatus||null,data.usedUrl||null).run()}
async function processSource(env:Env,source:Source,stats:any){const checkedAt=now();try{const fetched=await fetchSource(source),normalized=normalize(fetched.text,source),hash=await sha(normalized),prev=await env.DB.prepare('SELECT * FROM snapshots WHERE source_id=?').bind(source.id).first<any>();if(!prev){await env.DB.prepare('INSERT INTO snapshots (source_id,hash,content,checked_at,used_url) VALUES (?,?,?,?,?)').bind(source.id,hash,normalized,checkedAt,fetched.usedUrl).run();await upsertStatus(env,source.id,{state:'ok',message:'Linha de base criada; próximas alterações gerarão alerta',lastChecked:checkedAt,lastSuccess:checkedAt,httpStatus:fetched.httpStatus,usedUrl:fetched.usedUrl});stats.ok++;return}if(prev.hash===hash){await upsertStatus(env,source.id,{state:'ok',message:'Sem alteração relevante desde a última coleta',lastChecked:checkedAt,lastSuccess:checkedAt,httpStatus:fetched.httpStatus,usedUrl:fetched.usedUrl});stats.ok++;return}const snippets=changed(prev.content||'',normalized),fingerprint=await sha(`${source.id}|${snippets.join('|')}`);let created=false;if(snippets.join(' ').length>=80){const dup=await env.DB.prepare('SELECT id FROM events WHERE fingerprint=?').bind(fingerprint).first<any>();if(!dup){const a=await analyze(env,source,snippets),event=sanitize({...a,id:uid('auto'),sourceId:source.id,sourceName:source.name,sourceUrl:source.url,origin:source.origin,detectedAt:checkedAt,status:'new',evidence:snippets.slice(0,6).join('\n• ').slice(0,4000),automatic:true,fingerprint});await insertEvent(env,event);stats.created++;created=true}}await env.DB.prepare('UPDATE snapshots SET hash=?,content=?,checked_at=?,used_url=? WHERE source_id=?').bind(hash,normalized,checkedAt,fetched.usedUrl,source.id).run();await upsertStatus(env,source.id,{state:'ok',message:snippets.length?(created?'Alteração detectada e registrada':'Alteração detectada; sem novo alerta após deduplicação'):'Página mudou sem trecho relevante identificável',lastChecked:checkedAt,lastSuccess:checkedAt,httpStatus:fetched.httpStatus,usedUrl:fetched.usedUrl});stats.ok++}catch(err:any){const st=Number(err?.status||0),blocked=st===401||st===403||/antirobô|forbidden|access denied/i.test(err?.message||'');await upsertStatus(env,source.id,{state:blocked?'blocked':'error',message:blocked?'A fonte bloqueou a coleta automática. O link continua disponível para conferência e registro manual.':(err?.message||'Falha na coleta'),lastChecked:checkedAt,httpStatus:st||null});blocked?stats.blocked++:stats.failed++}}
const BUCKETS=[SOURCES.slice(0,2),SOURCES.slice(2,4),SOURCES.slice(4,6),SOURCES.slice(6,8)];
async function collect(env:Env,bucket:number|null=null){await ensureSeed(env);const startedAt=now(),stats={created:0,ok:0,blocked:0,failed:0};const targets=(bucket===null?SOURCES.filter(s=>s.monitor!=='manual'):BUCKETS[bucket]||[]).filter(s=>s.monitor!=='manual');for(const source of targets)await processSource(env,source,stats);const previous=await env.DB.prepare("SELECT value_json FROM meta WHERE key='last-run'").first<any>();const prev=safeJson<any>(previous?.value_json||null,{});const run={startedAt,finishedAt:now(),bucket,bucketSources:targets.map(s=>s.id),created:stats.created,ok:stats.ok,blocked:stats.blocked,failed:stats.failed,dayTotals:{created:(prev?.dayTotals?.created||0)+stats.created,ok:(prev?.dayTotals?.ok||0)+stats.ok,blocked:(prev?.dayTotals?.blocked||0)+stats.blocked,failed:(prev?.dayTotals?.failed||0)+stats.failed}};await env.DB.prepare("INSERT INTO meta(key,value_json) VALUES('last-run',?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json").bind(JSON.stringify(run)).run();return run}

async function importDashboard(env: Env, body: any) {
  let imported = 0;
  for (const raw of Array.isArray(body?.events) ? body.events : []) {
    const event = sanitize(raw);
    await insertEvent(env, event);
    imported++;
  }
  if (body?.lastRun) {
    await env.DB.prepare("INSERT INTO meta(key,value_json) VALUES('last-run',?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json")
      .bind(JSON.stringify(body.lastRun)).run();
  }
  if (body?.statuses && typeof body.statuses === 'object') {
    for (const [sourceId, st] of Object.entries<any>(body.statuses)) {
      if (SOURCES.some(s => s.id === sourceId) && st?.state) {
        await upsertStatus(env, sourceId, {
          state: st.state, message: st.message || 'Importado do Netlify', lastChecked: st.lastChecked || null,
          lastSuccess: st.lastSuccess || null, httpStatus: st.httpStatus || null, usedUrl: st.usedUrl || null
        });
      }
    }
  }
  return { imported };
}

function bucketFromCron(cron:string){if(cron==='0 9 * * *')return 0;if(cron==='15 9 * * *')return 1;if(cron==='30 9 * * *')return 2;if(cron==='45 9 * * *')return 3;return 0}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    if (!url.pathname.startsWith('/api/')) return env.ASSETS.fetch(request);

    try {
      if (url.pathname === '/api/health') {
        return json({ ok: true, platform: 'cloudflare', time: now() });
      }

      if (url.pathname === '/api/dashboard') {
        if (request.method === 'GET') {
          return json(await dashboard(env));
        }
        if (request.method === 'POST') {
          const event = await saveManual(env, await request.json());
          return json({ ok: true, event }, 201);
        }
        if (request.method === 'PATCH') {
          const event = await patchEvent(env, await request.json());
          return event
            ? json({ ok: true, event })
            : json({ error: 'Registro não encontrado' }, 404);
        }
        return json({ error: 'Método não permitido' }, 405);
      }

      if (url.pathname === '/api/import' && request.method === 'POST') {
        if (!env.COLLECTOR_TOKEN || request.headers.get('x-collector-token') !== env.COLLECTOR_TOKEN) {
          return json({ error: 'Não autorizado' }, 401);
        }
        return json({ ok: true, ...(await importDashboard(env, await request.json())) });
      }

      if (url.pathname === '/api/collect' && request.method === 'POST') {
        if (!env.COLLECTOR_TOKEN || request.headers.get('x-collector-token') !== env.COLLECTOR_TOKEN) {
          return json({ error: 'Não autorizado' }, 401);
        }
        return json(await collect(env, null));
      }

      return json({ error: 'Rota não encontrada' }, 404);
    } catch (err: any) {
      console.log(err);
      return json({ error: 'Falha no Radar', detail: err?.message || String(err) }, 500);
    }
  },

  async scheduled(controller: ScheduledController, env: Env, ctx: ExecutionContext) {
    const bucket = bucketFromCron(controller.cron);
    ctx.waitUntil(collect(env, bucket));
  }
};
